after_failure:
- cat **/target/surefire-reports/*.xml | grep -B 1 -A 10 "<error"
- cat **/target/failsafe-reports/*.xml | grep -B 1 -A 10 "<error"
after_success: bash <(curl -s https://codecov.io/bash)
before_script:
- echo MAVEN_OPTS=-Xmx1536m > ~/.mavenrc
jdk:
- oraclejdk8
language: java
script:
- touch NOW
- echo GIBSTUDYSTART $(date)
- mvn verify -B
- echo GIBSTUDYEND $(date)
- cd $TRAVIS_BUILD_DIR
- if [ "$TRAVIS_OS_NAME" == "osx" ];        then echo TESTNUM $(find . -name TEST-*.xml
  -newer NOW | wc -l);        else echo TESTNUM $(find -name TEST-*.xml -newer NOW
  | wc -l);        fi
services:
- docker
sudo: required
